### ISSUE TITLE
Compilation error with default-features = false

### ISSUE THREAD

**Issue by JBBgameich** [brave/adblock-rust#163]
After updating from v0.3.5 to 0.3.7, the compilation of the adblock crate failed.

```
   Compiling adblock v0.3.7
error[E0432]: unresolved import `addr`
 --> /home/jbb/.cargo/registry/src/github.com-1ecc6299db9ec823/adblock-0.3.7/src/url_parser/mod.rs:7:5
  |
7 | use addr::domain;
  |     ^^^^ use of undeclared crate or module `addr`

error: aborting due to previous error
```

Is it possible the following line is missing a ` #[cfg(feature = "embedded-domain-resolver")]` guard?
https://github.com/brave/adblock-rust/commit/6be3e1f82df4bffcc410517674db4e30f2654951#diff-616b8bc791a873602979bf6210d523c659ae7a35fea017d47c85dce2b77e7c57R7

**Comment by antonok-edm** [comment]
Yep, my bad for not checking closer - fixed in https://github.com/brave/adblock-rust/commit/14db0973669de829a469b722416d180022ffbe32.

Thanks for the report :smile:

**Comment by JBBgameich** [comment]
Thank you for the quick fix :)
